### ISSUE TITLE
Support Version 3.2.2

### ISSUE THREAD

**Issue by kkremerk** [nutso/redmine-plugin-recurring-tasks#106]
Hi guys,

I was not be able to install the master-Version on Redmine 3.2.1-0. 
Is the plugin not working ot the current Version? 
If so, did you plan to update the plugin for the current redmine version?

**Comment by nutso** [comment]
What error message(s) did you receive?

**Comment by amityk77** [comment]
hello...
please can you tell..whether it will be available for 3.2.x versions... ?

**Comment by nutso** [comment]
If you are not able to run it, please provide the error message. I have continued to run it successfully through 3.2.x and am currently on 3.3.0 without any modifications.
