### ISSUE TITLE
Recurring tasks ignore date settings

### ISSUE THREAD

**Issue by polozad** [nutso/redmine-plugin-recurring-tasks#107]
Hi. 
I have RM 3.1, and the latest plugin version. My tasks are recurring on cron no matter when they should be. For example - I created recurrence once in a month, and closed task after some actions. And it appears on next cron/rake job on next day instead waiting for next month. There are no error messages, just standard log records about creating. Where should I dig?

**Comment by nutso** [comment]
Hi @polozad, are the newly created tasks "due" incorrectly? The recurring task is created immediately after closing the previous one (if it's set to a non-fixed recurrence) -- but the dates should be set so that the end/due date is e.g. a month in advance.

**Comment by polozad** [comment]
Well, as I can see plugin should reopen task when desired date come. For example, I closed task at Jun 8 2016 and I need it to be reopen at Sep 8 2016. But it reopens on the next cronjob. 
Maybe I misunderstood something?

**Comment by nutso** [comment]
The expected behavior is for the task to reopen on the next cron job, but with the start/end dates updated with the new dates (e.g. the new end date would be 8 Sep 2016). This ensures the task shows up reports for planning purposes, but for the "next" running.

**Comment by polozad** [comment]
Ok, thank you!
This one can be closed.
