### ISSUE TITLE
Recurrence not copied/moved to new issue

### ISSUE THREAD

**Issue by Guite** [nutso/redmine-plugin-recurring-tasks#108]
Hi,

since a while the recurrence setting is not moved to the next issue in the cycle. So the recurrence keeps in the former ticket (of last iteration). So I need to remove it and readd it in the new ticket manually.

I tried to find the problem in the source, but did not cope with identifying where the recurrence is set in the newly created issue. Should that be part of the `copy` method called in https://github.com/nutso/redmine-plugin-recurring-tasks/blob/master/app/models/recurring_task.rb#L267 ?

I am using Redmine 3.2.3.

**Comment by nutso** [comment]
Hi @Guite, the recurrence should move to the new issue based on this line -- https://github.com/nutso/redmine-plugin-recurring-tasks/blob/master/app/models/recurring_task.rb#L295

Is there anything in your log files when the recurrence is created that might show an issue trying to save the updated recurrence information (the RecurringTask object that points to the new issue)?

**Comment by Guite** [comment]
No they are no additional log entries. Just one line about the new issue being created. Any way to raise the log level to show also notices or similar?

**Comment by Guite** [comment]
I've just migrating from Redmine to another system. Since this issue was probably specific to my environment or application of this plugin, I think it can be closed.
