### ISSUE TITLE
Recurring Tasks Issue

### ISSUE THREAD

**Issue by brontog** [nutso/redmine-plugin-recurring-tasks#110]
hi , i installed Recurring Tasks plugin in my Redmine, but does not work this plugin:
/bin/sh: cd /var/www/html/ && bundle exec rake RAILS_ENV=production redmine:recur_tasks: No such file or directory
please help me it's start plugin.

**Comment by nutso** [comment]
What is the folder name within your plugins directory?

It should be #{RAILS_ROOT}/plugins/**recurring_tasks** -- note the folder name 'recurring_tasks' must be verbatim.

**Comment by brontog** [comment]
Ok, thank you ))
