### ISSUE TITLE
Config with Crontab

### ISSUE THREAD

**Issue by DinhH** [nutso/redmine-plugin-recurring-tasks#127]
I'm having trouble with understand the crontab role.

where do I need to install crontab and how do I configure the cron job with the reoccurring tasks?

**Comment by nutso** [comment]
Crontab is a task scheduling utility that is included in Linux and Unix-based systems (such as MacOS). General installation and information about crontab is outside the scope of the plugin; more information can be found on Wikipedia (https://en.wikipedia.org/wiki/Cron). Would recommend questions be posted to stackoverflow.com. 

Information on configuring the plugin's specific cron jobs can be found in the README (https://github.com/nutso/redmine-plugin-recurring-tasks#configuration)
