### ISSUE TITLE
Compatibility with v4 ?

### ISSUE THREAD

**Issue by Ldiro** [nutso/redmine-plugin-recurring-tasks#132]
Hi,

Thank you for your work on this amazing plugin.

Do you plan to make it compatible with redmine 4 ?

Thanks,
Lilian DI ROSA

**Comment by nutso** [comment]
Hi Lillian, I no longer use Redmine, so am not investing additional time into this project (other than help with "how to", or pointers from time to time). I do not know the impact (if any) of Redmine 4 with regard to this plugin.

**Comment by Ldiro** [comment]
Ok I understand.

Main problems are not with Redmine 4 but with depreciations of Rails 5, like changing "before_filter" to "before_action" and so on.

I'm not a Rails developer but maybe I'll try to change with some list of depreciations I can find on the net.
