### ISSUE TITLE
Add recurrence like "third tuesday every month"

### ISSUE THREAD

**Issue by DonHege** [nutso/redmine-plugin-recurring-tasks#63]
Hi,

I'm sorry for posting this here, but I was not able to contact nutso outside of this repository. The README of the plugin says it's possible to add a reccurence like "every third Tuesday of the month". But how do I configure something like this? When I add a recurrence, this is what I get: 

![add-recurrence](https://cloud.githubusercontent.com/assets/10495080/6227271/b87f554c-b69d-11e4-900d-fac081cd4df2.PNG)

So, how do I add a recurrence like "every third Tuesday"? 

Thanks,
Marco

**Comment by nutso** [comment]
First, the issue that you are having recur must have a due date matching the recurrence pattern desired (e.g. on the 3rd Tuesday of a month).

Then, click Add recurrence and select "month" for the interval unit. This will bring up the "interval modifier" attribute, where you can select "on the x day", "on the x to last day", "on the x weekday", "on the x to last weekday"
