### ISSUE TITLE
Redmine 3.1 Support

### ISSUE THREAD

**Issue by frank-dspeed** [nutso/redmine-plugin-recurring-tasks#67]
Current Redmine Version is 3.1

Bundle complete! 30 Gemfile dependencies, 66 gems now installed.
Gems in the groups development and tests were not installed.
Bundled gems are installed into ./vendor/bundle.
Migrating plugins. Please be patient, this could take a while...
An error occurred while loading the routes definition of redmine-plugin-recurring-tasks plugin (/home/redmine/redmine/plugins/redmine-plugin-recurring-tasks/config/routes.rb): You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action".

**Comment by nutso** [comment]
I haven't published a new version per se as of yet, but the master branch now includes a contribution that enables support for Redmine 3.0+. Can you re-pull/download and try again?

**Comment by frank-dspeed** [comment]
Installation works probally problem that happens now is that the page cant be found: Page not found

The page you were trying to access doesn't exist or has been removed.

Back

url it trys is domain.tld/recurring_tasks

**Comment by Picazamora** [comment]
i have the same problem

**Comment by onewheelskyward** [comment]
It's worth noting that the current Redmine version is actually 3.0.1.  Performing the rake redmine:plugins:migrate also borks the /issues route somehow.  I'm going to debug this when I find some time.

**Comment by jonhalle** [comment]
As a workaround on a new redmine install (ie with nothing to upgrade) I commented out the content of the 'up' function in recurring_tasks/db/migrate/004_set_default_modifier_for_existing_monthly_issues.rb and the install went ahead, plugin appears to work. not a fix but may be useful to others in the interim.

redmine:3.01 from debian package. recurring_tasks: git clone of master.

**Comment by bcorepcs** [comment]
Does this apply to Redmine 2.5?

Brian Wajerski
Core Computer Solutions
brian@corepcs.com<mailto:brian@corepcs.com>
Help desk:414-727-1240
Direct: 414-727-3266
[cid:image001.png@01CFE9E3.73DB8CD0]
Technology Solutions For Your Business

**Comment by jonhalle** [comment]
I don't know about Redmine 2.5 - it was just a workaround to get this running on Redmine 3.0x

**Comment by Slind14** [comment]
doesn't work with newer builds anymore :(

**Comment by nutso** [comment]
I fixed the migration for the next release (1.5), and a previous contribution already in master fixed the routes. 

@bcorepcs these issues only impacted Redmine 3+ because the core Rails version changed.
