### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by L1ghtn1ng** [nutso/redmine-plugin-recurring-tasks#73]
Under the readme you have ```* */4 * * * /bin/sh "cd {path_to_redmine} && bundle exec rake RAILS_ENV=production redmine:recur_tasks" >> log/cron_rake.log 2>&1``` is it supposed to be ```* */4 * * * /bin/sh "cd {path_to_redmine} && bundle exec rake RAILS_ENV=production redmine:recurring_tasks" >> log/cron_rake.log 2>&1``` ?

**Comment by nutso** [comment]
No ... does that work for you?

recur_tasks is what the task is defined as (in lib/tasks/recurring_tasks.rake, ... `task :recur_tasks => ` ...).

**Comment by L1ghtn1ng** [comment]
Okay thanks
