### ISSUE TITLE
Feature request: re-open tasks instead of duplicating.

### ISSUE THREAD

**Issue by dispmaxstaff** [nutso/redmine-plugin-recurring-tasks#74]
Just some flag for recurrence entry: duplicate or just re-open.
This option will be especially useful for tasks that are opened on per 1 day basis to prevent issue number bloat. Also this feature is useful for tasks that are used for routine metrics gathering, so you can see results right in the issue instead of going through linked issues.

**Comment by nutso** [comment]
Similar request to #45. Added to list of features requested. Will follow up on this closed ticket when the feature is available.
