### ISSUE TITLE
Cron job issues

### ISSUE THREAD

**Issue by bcorepcs** [nutso/redmine-plugin-recurring-tasks#75]
So I have been struggling to get the cron job to work properly on my Redmine 2.5 server. I've tried adjusting my paths and syntax in the cron job multiple times without success. The closest I got to having this plugin work was when I was testing cron command syntax and figured out I could duplicate the jobs but it wasn't closing/removing the old job.

With that said, I'm running Bitnami's Redmine 2.5 on Ubuntu 12.10 LTS (bitnami.com) so my paths are different than a "home rolled" setup.

Here is what I have currently for my cron job (and I know this doesn't work but it prevented duplication spam on my tasks)

/bin/sh "cd /opt/bitnami/apps/redmine/htdocs/ && bundle exec rake RAILS_ENV=production redmine:recur_tasks" >> /opt/bitnami/apps/redmine/htdocs/log/cron_rake.log 2>&1

And this doesn't seem to be working at all. The only thing that stands out to me is the: rake RAILS_ENV=production redmine:recur_tasks"

section. I would've expected to see "recurring_tasks" instead of "recur_tasks"  but I digress.

Can you please help me with this? I'll gladly provide more information as needed.

**Comment by nutso** [comment]
re: the digression -- recur_tasks is the task name (defined in lib/tasks/recurring_tasks.rake) that we are calling. It's really just a convenience method for command-line syntax; you would have the same impact from using `rails r RecurringTask.add_recurrences!` (which is defined in the RecurringTask model).

**Comment by nutso** [comment]
Here's what I set my cron job to in Bitnami Redmine 3.03/Ubuntu --

`[timestring] cd /opt/bitnami/apps/redmine/htdocs && bundle exec rake RAILS_ENV=production redmine:recur_tasks >> log/recurring_tasks.log 2>&1`

Looks like invoking bash (/bin/sh) is perhaps not necessary in Ubuntu.
