### ISSUE TITLE
Undefined local variable or method `define_user' for

### ISSUE THREAD

**Issue by marius-balteanu** [nutso/redmine-plugin-recurring-tasks#86]
Filling an user_id in the plugin settings (for field Attribute issue journals to user id) generates the below error when I run the rake task:

<pre>
(in /var/www/hr_redmine)
Checking for Redmine recurring tasks.
rake aborted!
NameError: undefined local variable or method `define_user' for #<RecurringTask:0x00000008b50f88>
/usr/local/rvm/gems/ruby-2.1.5/gems/activemodel-3.2.21/lib/active_model/attribute_methods.rb:407:in `method_missing'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.21/lib/active_record/attribute_methods.rb:149:in `method_missing'
/var/www/hr_redmine/plugins/recurring_tasks/app/models/recurring_task.rb:268:in `recur_issue_if_needed!'
/var/www/hr_redmine/plugins/recurring_tasks/app/models/recurring_task.rb:316:in `block in add_recurrences!'
/var/www/hr_redmine/plugins/recurring_tasks/app/models/recurring_task.rb:315:in `each'
/var/www/hr_redmine/plugins/recurring_tasks/app/models/recurring_task.rb:315:in `add_recurrences!'
/var/www/hr_redmine/plugins/recurring_tasks/lib/tasks/recurring_tasks.rake:12:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
</pre>

The user id exists and has administration rights.

Also, if I remove the user id, when I run the rake task I receive another error, but the recurrent task is added:

<pre>
(in /var/www/hr_redmine)
Checking for Redmine recurring tasks.
Recurring 5192: Task recurent de acum o saptamana (11.06.2015), created or reopened 5199: Task recurent de acum o saptamana (18.06.2015)
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: You couldn`t save issues with this tracker
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.21/lib/active_record/validations.rb:56:in `save!'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.21/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.21/lib/active_record/transactions.rb:264:in `block in save!'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.21/lib/active_record/transactions.rb:264:in `save!'
/var/www/hr_redmine/plugins/recurring_tasks/app/models/recurring_task.rb:274:in `recur_issue_if_needed!'
/var/www/hr_redmine/plugins/recurring_tasks/app/models/recurring_task.rb:316:in `block in add_recurrences!'
/var/www/hr_redmine/plugins/recurring_tasks/app/models/recurring_task.rb:315:in `each'
/var/www/hr_redmine/plugins/recurring_tasks/app/models/recurring_task.rb:315:in `add_recurrences!'
/var/www/hr_redmine/plugins/recurring_tasks/lib/tasks/recurring_tasks.rake:12:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:recur_tasks
(See full trace by running task with --trace)
</pre>

I'm using the latest version of the plugin from master and Redmine 2.6.1 with Luxury Buttons.

**Comment by nutso** [comment]
I fixed the issue for when the user id is provided and pushed to master. 

Since the error generated by Luxury Buttons when the validation fails is a generic error, I cannot suppress the second error with a nice message (i.e. direct the admin to configure the setting). Otherwise, if any error occurs when saving the issue, the user could get misleading information.
