### ISSUE TITLE
redmine:recur_tasks launched with errors and aborted

### ISSUE THREAD

**Issue by insspb** [nutso/redmine-plugin-recurring-tasks#90]
I am trying to launch on my test server (from redmine directory) but it does not work. 

Output:
[redmine@redmine plugins]$ cd /srv/redmine/ && bundle exec rake RAILS_ENV=production redmine:recur_tasks
Checking for Redmine recurring tasks.
rake aborted!
NoMethodError: undefined method `-' for nil:NilClass
/srv/redmine/plugins/recurring_tasks/app/models/recurring_task.rb:252:in `recur_issue_if_needed!'
/srv/redmine/plugins/recurring_tasks/app/models/recurring_task.rb:317:in `block in add_recurrences!'
/srv/redmine/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
/srv/redmine/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
/srv/redmine/plugins/recurring_tasks/app/models/recurring_task.rb:316:in `add_recurrences!'
/srv/redmine/plugins/recurring_tasks/lib/tasks/recurring_tasks.rake:12:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine:recur_tasks
(See full trace by running task with --trace)
[redmine@redmine ~]$

Output with --trace
[redmine@redmine ~]$ cd /srv/redmine/ && bundle exec rake RAILS_ENV=production redmine:recur_tasks --trace
** Invoke redmine:recur_tasks (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:recur_tasks
Checking for Redmine recurring tasks.
rake aborted!
NoMethodError: undefined method `-' for nil:NilClass
/srv/redmine/plugins/recurring_tasks/app/models/recurring_task.rb:252:in `recur_issue_if_needed!'
/srv/redmine/plugins/recurring_tasks/app/models/recurring_task.rb:317:in `block in add_recurrences!'
/srv/redmine/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
/srv/redmine/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
/srv/redmine/plugins/recurring_tasks/app/models/recurring_task.rb:316:in `add_recurrences!'
/srv/redmine/plugins/recurring_tasks/lib/tasks/recurring_tasks.rake:12:in `block (2 levels) in <top (required)>'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/srv/redmine/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/srv/redmine/.rvm/rubies/ruby-2.2.1/bin/rake:33:in `<main>'
Tasks: TOP => redmine:recur_tasks
[redmine@redmine ~]$

**Comment by insspb** [comment]
Tested on both versions. Develop and master.

**Comment by nutso** [comment]
recreated the issue when the issue that's recurring does not have either a start or due date. resolved in develop and master, will be included in next release.

**Comment by insspb** [comment]
Works fine now. Thx.
