### ISSUE TITLE
cann't uninstall plugin

### ISSUE THREAD

**Issue by ddk85** [nutso/redmine-plugin-recurring-tasks#93]
Got an error:
# rake redmine:plugins:migrate NAME=recurring_tasks VERSION=0 RAILS_ENV=production
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
Migrating recurring_tasks (Recurring Tasks (Issues))...
==  AddIntervalModifierField: reverting =======================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

ActiveRecord::IrreversibleMigration/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration/command_recorder.rb:42:in `block in inverse'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration/command_recorder.rb:40:in `map'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration/command_recorder.rb:40:in `inverse'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:401:in `block (3 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:358:in `revert'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:400:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:399:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:389:in `migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:528:in `migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:777:in `call'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:777:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:719:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `each'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:574:in `down'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:555:in `migrate'
path/lib/redmine/plugin.rb:469:in `migrate_plugin'
path/lib/redmine/plugin.rb:441:in `migrate'
path/lib/redmine/plugin.rb:452:in `migrate'
path/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
ActiveRecord::IrreversibleMigration: ActiveRecord::IrreversibleMigration
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration/command_recorder.rb:42:in `block in inverse'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration/command_recorder.rb:40:in `map'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration/command_recorder.rb:40:in `inverse'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:401:in `block (3 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:358:in `revert'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:400:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:399:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:389:in `migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:528:in `migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:777:in `call'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:777:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:719:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `each'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:700:in `migrate'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:574:in `down'
/usr/local/rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/migration.rb:555:in `migrate'
path/lib/redmine/plugin.rb:469:in `migrate_plugin'
path/lib/redmine/plugin.rb:441:in `migrate'
path/lib/redmine/plugin.rb:452:in `migrate'
path/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

**Comment by nutso** [comment]
What version are you using? You might need to update to the latest version and then uninstall; none of the migrations are irreversible anymore.
