### ISSUE TITLE
Pluralize problem in Russian

### ISSUE THREAD

**Issue by insspb** [nutso/redmine-plugin-recurring-tasks#94]
I am finishing updated translation to Russian. But I faced several issues like this one:
![image](https://cloud.githubusercontent.com/assets/1916759/8580565/034a3264-25c4-11e5-8374-3453baf2d0c9.png)

Some function just add English "s" to Russian word. 
How can i fix it? Or I need to delete pluralize function from code?

**Comment by dominch** [comment]
same for polish :( 
also there is a problem with field_recurrence field, that one is pluralized in English way too, so we needed to find word ending with "s".

**Comment by nutso** [comment]
You can provide explicit pluralization by providing a :count attribute in the locale file (:count: 1 for the singular form and :count: 2 for the plural form).

From http://guides.rubyonrails.org/i18n.html#pluralization --

"The :count interpolation variable has a special role in that it both is interpolated to the translation and used to pick a pluralization from the translations according to the pluralization rules defined by CLDR"

**Comment by dominch** [comment]
There is error when pluralization is added to translation files: 
<pre>
  field_recurrence:
    one: "Cykl"
    other: "Cykle"
</pre>
gives error: ERROR: undefined method `pluralize' for {:one=>"cykl", :other=>"cykle"}:Hash
it works when code inside template is changed to <%= t("field_recurrence", count: 2) %>
how can I make pluralize function to work?

**Comment by Kozzi11** [comment]
Why this is closed? Error is still there

**Comment by nutso** [comment]
The original issue was closed; looks like a separate issue was added after the issue was closed. Need to be opened as a new issue.

**Comment by Kozzi11** [comment]
make sense :)
